language: python
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.3
install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=py27-django-18
  - TOXENV=py33-django-18
  - TOXENV=py34-django-18
  - TOXENV=py35-django-18
  - TOXENV=py27-django-19
  - TOXENV=py34-django-19
  - TOXENV=py35-django-19
  - TOXENV=py27-django-110
  - TOXENV=py34-django-110
  - TOXENV=py35-django-110
